spring:
  application:
    name: micro-products
  datasource:
    url: jdbc:does-not-need-db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5

miapp:
  mensaje: "Hola desde el microservicio de productos"
